=== aranaur/pstk/Tonn_Vaher/Eksam/xsd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://www.w3.org/2001/XMLSchema"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<!-- Players use field hours -->
	<xs:element name="field">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="players">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="player" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="name" type="xs:string" />
									</xs:sequence>
									<!-- How can the system recognize that it is
											an ID? -->
									<xs:attribute name="p_id" type="xs:ID" use="required">
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="field_hours">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="field_hour" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="start" type="xs:time" />
										<xs:element name="end" type="xs:time" />
									</xs:sequence>
									<xs:attribute name="f_id" type="xs:ID" use="required">
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="usage" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="u_id" type="xs:ID" use="required">
						</xs:attribute>
						<xs:attribute name="f_id" type="xs:IDREF" use="required">
						</xs:attribute>
						<xs:attribute name="p_id" type="xs:IDREF" use="required">
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== aranaur/pstk/Tonn_Vaher/Eksam/xml2.xml
<?xml version="1.0" encoding="UTF-8"?>
<field xmlns="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.w3.org/2001/XMLSchema xsd.xsd">

<!-- Players use field hours -->
	<players>
		<player p_id="_4">
			<name>Meelis</name>
		</player>
		<player p_id="_5">
			<name>Andres</name>
		</player>
		<player p_id="_7">
			<name>Anne</name>
		</player>
	</players>
	<field_hours>
		<field_hour f_id="_12">
			<start>12:00:00</start>
			<end>13:00:00</end>
		</field_hour>
		<field_hour f_id="_15">
			<start>15:00:00</start>
			<end>16:00:00</end>
		</field_hour>
		<field_hour f_id="_18">
			<start>18:00:00</start>
			<end>19:00:00</end>
		</field_hour>
	</field_hours>
	<!-- Where can I see any existing players on field hours? -->
	<usage u_id="_1" f_id="_12" p_id="_1" />
	<usage u_id="_2" f_id="_15" p_id="_2" />
	<usage u_id="_3" f_id="_18" p_id="_3" />
</field>
