=== aranaur/pstk/maiko kallus/Margistuskeeled/xml/xsd/xsd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://www.w3.org/2001/XMLSchema"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="activities">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="activity" type="xs:string" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="activity">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="when" type="xs:string" />
				<xs:element name="message" type="xs:string" />
			</xs:sequence>
			<xs:anyAttribute />
		</xs:complexType>
	</xs:element>
	<xs:element name="when">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="day" type="xs:integer" />
				<xs:element name="month" type="xs:integer" />
				<xs:element name="year" type="xs:integer" />
				<xs:element name="hour" type="xs:integer" />
				<xs:element name="minute" type="xs:integer" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="message" type="xs:string" />
</xs:schema>

=== aranaur/pstk/maiko kallus/Margistuskeeled/xml/xml.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?><!-- proloog -->
<!DOCTYPE activity SYSTEM "dtd.dtd">
<activities>
	<!-- Inglise keele test -->
	<activity name="english" xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.w3.org/2001/XMLSchema xsd.xsd">
		<when>
			<day>18</day>
			<month>11</month>
			<year>2014</year>
			<hour>9</hour>
			<minute>00</minute>
		</when>
		<message><![CDATA[Kindlasti valmistuge inglise keele testiks ette.]]></message>
	</activity>
	<!-- Spordipäev -->
	<activity name="sportsday">
		<when>
			<day>22</day>
			<month>11</month>
			<year>2014</year>
			<hour>9</hour>
			<minute>00</minute>
		</when>
		<message><![CDATA[Tuletame kõigile meelde et on vaja kaasa võtta võimlemis riided!]]></message>
	</activity>
	<!-- Male turniir kõikidele huvilistele! -->
	<activity name="chess_tournament">
		<when>
			<day>26</day>
			<month>11</month>
			<year>2014</year>
			<hour>9</hour>
			<minute>00</minute>
		</when>
		<message><![CDATA[Kõikidel huvilistel palume registreerida huvijuhi juures!]]></message>
	</activity>
</activities>
