=== aranaur/pstk/kaia_kuunal/realEstate.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT Objects (Object)*>
<!ELEMENT Object (Address, ObjectType, Description?, Story?, EstateAgent,
					RoomArea, TotalArea?, AreaUnit, Price, Bathrooms,
					Bedrooms, Stories?, HasYard?, HasBalcony?)>
<!ELEMENT Address (Street, City, Region)>
<!ELEMENT ObjectType (#PCDATA)>
<!ELEMENT Description (#PCDATA>
<!ELEMENT Story (#PCDATA)>
<!ELEMENT EstateAgent EMPTY>
<!ELEMENT RoomArea (#PCDATA)>
<!ELEMENT TotalArea (#PCDATA)>
<!ELEMENT AreaUnit (#PCDATA)>
<!ELEMENT Price (#PCDATA)>
<!ELEMENT Bathrooms (#PCDATA)>
<!ELEMENT Bedrooms (#PCDATA)>
<!ELEMENT Stories (#PCDATA)>
<!ELEMENT Stories (#PCDATA)>
<!ELEMENT HasYard EMPTY>
<!ELEMENT HasBalcony EMPTY>
<!ELEMENT Street (#PCDATA)>
<!ELEMENT City (#PCDATA)>
<!ELEMENT Region (#PCDATA)>

<!ATTLIST Object id ID #REQUIRED>
<!ATTLIST EstateAgent id IDREF #REQUIRED>

=== aranaur/pstk/kaia_kuunal/realEstateDtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Objects SYSTEM "realEstate.dtd">
<!-- Real estate objects -->
<Objects>
	<Object id="o1">
		<Address>
			<Street>Tamme 12</Street>
			<City>Tallinn</City>
			<Region>Harjumaa</Region>
		</Address>
		<ObjectType>House</ObjectType>
		<Description><![CDATA[Kena maja <strong>linna piiril</strong>.]]></Description>
		<EstateAgent id="a6" />
		<RoomArea>220</RoomArea>
		<TotalArea>1000</TotalArea>
		<AreaUnit>m2</AreaUnit>
		<Price>140500.00</Price>
		<Bathrooms>2</Bathrooms>
		<Bedrooms>2</Bedrooms>
		<Stories>2</Stories>
		<HasYard />
	</Object>
	<Object id="o2">
		<Address>
			<Street>Kuuse 1-25</Street>
			<City>Viljandi</City>
			<Region>Viljandimaa</Region>
		</Address>
		<ObjectType>Apartment</ObjectType>
		<Description><![CDATA[Kuubik hruštšovkas.]]></Description>
		<Story>2</Story>		
		<EstateAgent id="a4" />
		<RoomArea>32</RoomArea>
		<AreaUnit>m2</AreaUnit>
		<Price>31549.99</Price>
		<Bathrooms>1</Bathrooms>
		<Bedrooms>1</Bedrooms>
	</Object>
	<Object id="o3">
		<Address>
			<Street>Kännu 12-3</Street>
			<City>Tartu</City>
			<Region>Tartumaa</Region>
		</Address>
		<ObjectType>Apartment</ObjectType>
		<Description><![CDATA[Normaalse vaatega neljatoaline korter.]]></Description>
		<Story>5</Story>		
		<EstateAgent id="a2" />
		<RoomArea>74.4</RoomArea>
		<AreaUnit>m2</AreaUnit>
		<Price>100549.99</Price>
		<Bathrooms>1</Bathrooms>
		<Bedrooms>3</Bedrooms>
		<HasBalcony />
	</Object>	
</Objects>
