=== aranaur/pstk/armin_siig/eksam/inimesed_suhtlevad_inimesega.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT chatbox (humans, humans_humans)>
<!ELEMENT humans (human+)>
<!ELEMENT human (firstname, lastname)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ATTLIST human id ID #REQUIRED>
<!ELEMENT humans_humans (human_human+)>
<!ELEMENT human_human EMPTY>
<!ATTLIST human_human id IDREFS #REQUIRED>

=== aranaur/pstk/armin_siig/eksam/inimesed_suhtlevad_inimesega_dtd.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE chatbox SYSTEM "inimesed_suhtlevad_inimesega.dtd">
<chatbox>
	<humans>
		<human id="a1">
			<firstname>armin</firstname>
			<lastname>hiir</lastname>
		</human>
		<human id="a2">
			<firstname>hiir</firstname>
			<lastname>armin</lastname>
		</human>
		<human id="a3">
			<firstname>laev</firstname>
			<lastname>kaev,</lastname>
		</human>
	</humans>
	<humans_humans>
		<human_human id="a1 a2"></human_human>
		<human_human id="a1 a3"></human_human>
	</humans_humans>
</chatbox>
