=== aranaur/pstk/armin_siig/eksam/kutusedSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
ˇˇ<xs:schema targetNamespace="http://www.w3.org/2001/XMLSchema"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="station">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="fuels">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="fuel" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="price" type="xs:decimal" />
									</xs:sequence>
									<xs:attribute name="id" type="xs:ID" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>

					</xs:complexType>
				</xs:element>
				<xs:element name="people">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="client" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="id" type="xs:ID" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>

					</xs:complexType>
				</xs:element>
				<xs:element name="people_buying">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="client_fuel" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="amount" type="xs:decimal" />
									</xs:sequence>
									<xs:attribute name="id_client" type="xs:IDREF" />
									<xs:attribute name="id_fuel" type="xs:IDREF" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== aranaur/pstk/armin_siig/eksam/kutused_XSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<station xmlns="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.w3.org/2001/XMLSchema kutusedSchema.xsd">
	<fuels>
		<fuel id="s1">
			<price>18</price>
		</fuel>
		<fuel id="s2">
			<price>19</price>
		</fuel>
	</fuels>
	<people>
		<client id="d1" />
	</people>
	<people_buying>
		<client_fuel id_client="d1" id_fuel="s1">
			<amount>10</amount>
			
		</client_fuel>
		<client_fuel  id_client="d1" id_fuel="s2"> 
			<amount>100</amount>
		</client_fuel>
	</people_buying>
</station>
