=== aranaur/pstk/armin_siig/databases/eksam/energy.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT ENERGY (ENERGIES, PRODUCERS)>
<!ELEMENT ENERGIES (ENERGY_TYPE+)>
<!ELEMENT ENERGY_TYPE (ENERGY_NAME,RENEWABLE?, PRICE)>
<!ATTLIST ENERGY_TYPE id ID #REQUIRED>
<!ELEMENT ENERGY_NAME (#PCDATA)>
<!ELEMENT RENEWABLE EMPTY>
<!ELEMENT PRICE (#PCDATA)>
<!ELEMENT PRODUCERS (PRODUCER+)>
<!ELEMENT PRODUCER (PRODUCER_NAME)>
<!ELEMENT PRODUCER_NAME (#PCDATA)>
<!ATTLIST PRODUCER id ID #REQUIRED>
<!ELEMENT PRODUCERS_HAS_ENERGIES (PRODUCER_HAS_ENERGY*)>
<!ELEMENT PRODUCER_HAS_ENERGY EMPTY>
<!ATTLIST PRODUCER_HAS_ENERGY ENERGY_TYPE IDREFS #REQUIRED PRODUCER IDREFS #REQUIRED>

=== aranaur/pstk/armin_siig/databases/eksam/energy_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE toitumine SYSTEM "energy.dtd">
<ENERGY>
	<ENERGIES>
		<ENERGY_TYPE id="A1">
			<ENERGY_NAME>p√µlevkivi</ENERGY_NAME>
			<RENEWABLE />
			<PRICE>100</PRICE>
		</ENERGY_TYPE>
		<ENERGY_TYPE id="B1">
			<ENERGY_NAME>solar energy</ENERGY_NAME>
			<RENEWABLE />
			<PRICE>50</PRICE>
		</ENERGY_TYPE>
		<ENERGY_TYPE id="C1">
			<ENERGY_NAME>nafta</ENERGY_NAME>
			<RENEWABLE/>
			<PRICE>200</PRICE>
		</ENERGY_TYPE>
	</ENERGIES>
	<PRODUCERS>
		<PRODUCER id="s1">
			<PRODUCER_NAME>EE
			</PRODUCER_NAME>
		</PRODUCER>
		<PRODUCER id="s2">
			<PRODUCER_NAME>Norra
			</PRODUCER_NAME>
		</PRODUCER>
		<PRODUCER id="s3">
			<PRODUCER_NAME>Norra
			</PRODUCER_NAME>
		</PRODUCER>
	</PRODUCERS>

</ENERGY>
