=== aranaur/pstk/maiko kallus/eksam/eksam.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT eksam (taimed, kasvukohad, omadused)>
<!ELEMENT taimed (taime_nim+, ladina_nim+)>
<!ELEMENT omadused (maitseomadus*, pikkus?, lehe_kuju?, kroonlehe_varv*)>
<!ELEMENT kasvukohad (kasvukoht)>
<!ELEMENT kasvukoht (#PCDATA)>
<!ELEMENT taime_nim (#PCDATA)>
<!ELEMENT ladina_nim (#PCDATA)>
<!ELEMENT maitseomadus EMPTY>
<!ELEMENT pikkus EMPTY>
<!ELEMENT lehe_kuju EMPTY>
<!ELEMENT kroonlehe_varv EMPTY>


<!ATTLIST taimed taimed_id ID #REQUIRED>
<!ATTLIST kasvukohad kasvukohad_id ID #REQUIRED>
<!ATTLIST omadused omadused_id ID #REQUIRED>

=== aranaur/pstk/maiko kallus/eksam/eksam_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE eksam SYSTEM "eksam.dtd" >
<eksam>
  <taimed taimed_id="idvalue0">
    <taime_nim>taime_nim</taime_nim>
    <ladina_nim>ladina_nim</ladina_nim>
  </taimed>
  <kasvukohad kasvukohad_id="idvalue1">
    <kasvukoht>kasvukoht</kasvukoht>
  </kasvukohad>
  <omadused omadused_id="idvalue2">
  	<maitseomadus></maitseomadus>
  	<pikkus></pikkus>
  	<lehe_kuju></lehe_kuju>
  	<kroonlehe_varv></kroonlehe_varv>
  </omadused>
</eksam>
