=== aranaur/pstk/Martin Blasen/toiduained.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT toiduainete_liigid (liigid,toiduained, jaotused)>
<!ELEMENT liigid (liik+)>
<!ELEMENT liik (nimi)>
<!ELEMENT nimi (#PCDATA)>
<!ATTLIST liik ID ID #REQUIRED>

<!ELEMENT toiduained (toiduaine+)>
<!ELEMENT toiduaine (nimi)>
<!ATTLIST toiduaine ID ID #REQUIRED>

<!ELEMENT jaotused (jaotus+)>
<!ELEMENT jaotus EMPTY>
<!ATTLIST jaotus IDliik IDREF #REQUIRED>
<!ATTLIST jaotus IDtoiduaine IDREFS #REQUIRED>

=== aranaur/pstk/Martin Blasen/Toiduained.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE toiduained SYSTEM "toiduained.dtd">

<toiduainete_liigid>
	<liigid>
		<liik ID="liik1">
			<nimi>vedelikud</nimi>
		</liik>
		<liik ID="liik2">
			<nimi>k채채ritatud toidud</nimi>
		</liik>
		<liik ID="liik3">
			<nimi>tihedada/천lised valgud</nimi>
		</liik>
	</liigid>
	<toiduained>
		<toiduaine ID="aine1">
			<nimi>vesimeloni mahl</nimi>
		</toiduaine>
		<toiduaine ID="aine2">
			<nimi>nisurohu mahl</nimi>
		</toiduaine>
		<toiduaine ID="aine3">
			<nimi>kali</nimi>
		</toiduaine>
		<toiduaine ID="aine4">
			<nimi>seemnejuust/-soust</nimi>
		</toiduaine>
		<toiduaine ID="aine5">
			<nimi>esseeni kuivikud</nimi>
		</toiduaine>
		<toiduaine ID="aine6">
			<nimi>hapukapsas</nimi>
		</toiduaine>
		<toiduaine ID="aine7">
			<nimi>p채hkel</nimi>
		</toiduaine>
		<toiduaine ID="aine8">
			<nimi>avokaado</nimi>
		</toiduaine>
		<toiduaine ID="aine9">
			<nimi>mandel</nimi>
		</toiduaine>
	</toiduained>
	
	<jaotused>
		<jaotus IDliik="liik1" IDtoiduaine="aine1 aine2 aine3" />
	</jaotused>

</toiduainete_liigid>
