<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE signature [
<!ELEMENT signature (teacher, banks+)>

<!ELEMENT teacher (name, title, streetAddress, phoneNumbers, bankAccounts)>
<!ATTLIST teacher  id ID #REQUIRED>

<!ELEMENT name (firstName, lastName)>

<!ELEMENT firstName (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>

<!ELEMENT title (#PCDATA)>

<!ELEMENT streetAddress (#PCDATA)>
<!ATTLIST streetAddress xml:space (default|preserve) "preserve">

<!ELEMENT phoneNumbers (landLine, mobile)>

<!ELEMENT landLine (#PCDATA)>
<!ELEMENT mobile (#PCDATA)>

<!ELEMENT bankAccounts (bankAccount+)>
<!ATTLIST bankAccount id ID #REQUIRED
	order CDATA #IMPLIED
	idOfBank IDREF #REQUIRED>
<!ELEMENT bankAccount EMPTY>

<!ELEMENT banks (bank+)>

<!ELEMENT bank (nameOfBank)>
<!ATTLIST bank id ID #REQUIRED>

<!ELEMENT nameOfBank (#PCDATA)>
<!ATTLIST nameOfBank xml:lang NMTOKEN #FIXED "et">
]>
<signature>
	<teacher id="t37804080345">
		<name>
			<firstName>Kalmer</firstName>
			<lastName>Piiskop</lastName>
		</name>
		<title>MSc.</title>
		<streetAddress xml:space="preserve"><![CDATA[
        Instituudi tee 3-27<br/>
        EE76902 Harku      <br/>
        Harku              <br/>
        Harjumaa           <br/>
        European Union
    ]]></streetAddress>
		<phoneNumbers>
			<landLine>3726524228</landLine>
			<mobile>37256204556</mobile>
		</phoneNumbers>
		<bankAccounts>
			<bankAccount id="EE747700771000356083" order="1"
				idOfBank="LHVBEE22" />
			<bankAccount id="EE893300336314570000 " idOfBank="FOREEE2X" />
			<bankAccount id="EE182200001107112667" idOfBank="HABAEE2X" />
		</bankAccounts>
	</teacher>
	<banks>
		<bank id="LHVBEE22">
			<nameOfBank>AS LHV Pank</nameOfBank>
		</bank>
		<bank id="FOREEE2X">
			<nameOfBank>Danske Bank A/S Eesti filiaal</nameOfBank>
		</bank>
		<bank id="HABAEE2X">
			<nameOfBank>Swedbank AS</nameOfBank>
		</bank>
	</banks>
</signature>
