=== aranaur/pstk/armin_siig/KNIP/kasutaja.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://www.w3.org/2001/XMLSchema"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="student">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="sex">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="male|female" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>

				<xs:element name="username">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="3" />
							<xs:maxLength value="8" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>

				<xs:element name="firstname">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="3" />
							<xs:maxLength value="15" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>

				<xs:element name="secondname">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="3" />
							<xs:maxLength value="10" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>

				<xs:element name="e-mail" type="xs:string">
				</xs:element>
				<xs:element name="password" maxOccurs="unbounded">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="([a-zA-Z0-9])+" />
							<xs:minLength value="8" />
							<xs:maxLength value="15" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== aranaur/pstk/armin_siig/KNIP/kasutaja.xml
<?xml version="1.0" ?>
<student xmlns="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.w3.org/2001/XMLSchema kasutaja.xsd">
	<sex>male</sex>
	<username>Juhan1</username>
	<firstname>Juhan Kalle</firstname>
	<secondname>Malle</secondname>
	<e-mail>Juhan94@gmail.com</e-mail>
	<password>passw0rd1</password>
	<password>passw0rd1</password>
</student>
