=== aranaur/pstk/Tarmo/new.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.w3schools.com"
xmlns="http://www.w3schools.com"
elementFormDefault="qualified">
<xs:element name="action">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="spacedname" type="xs:normalizedString"/>
			<xs:element name="nowhitespacename" type="xs:token"/>
			<xs:element name="start_date" type="xs:date"/>
			<xs:element name="start_time" type="xs:time"/>
			<xs:element name="end" type="xs:dateTime"/>
			<xs:element name="duration" type="xs:duration"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
</xs:schema>

=== aranaur/pstk/Tarmo/new.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE action>
<action xmlns="http://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.w3schools.com new.xsd">
	<name>Laulmine</name>
	<spacedname>		Laulmine		joi
		</spacedname>
	<nowhitespacename> 	 	lll 	 Laulmine 
		 	 </nowhitespacename>
	<start_date>2014-12-03</start_date>
	<start_time>09:00:00</start_time>
	<end>2014-12-04T12:00:00</end>
	<duration>P1DT3H</duration>
</action>
